# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=140, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='Travel Date From')),
                ('end_date', models.DateField(verbose_name='Travel Date To')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_creator', to=settings.AUTH_USER_MODEL)),
                ('join', models.ManyToManyField(related_name='joined_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
